Feat/#94 new plan
Pullanner/pullanner-web pull request #103
Opened 2023-09-05 13:40 UTC by jaypedia

## Issues
- #94 

## Tasks Done 
- [x] Plan 페이지의 Plan Button 구현(근력 키우기 플랜 & 동작 마스터 플랜)
   - [x] 유저가 모든 풀업 운동을 마스터했을 경우 '동작 마스터 플랜'이 생성되지 않도록 구현 
   - [x] 오늘 날짜 이전에는 플랜을 생성할 수 없도록 구현 
- [x] New Plan 페이지 구현 
  - [x] 풀업 운동을 선택 시, 하단에 테이블 형태로 Row가 추가되도록 구현  
  - [x] Form 내용을 모두 채워야 저장 버튼이 활성화되도록 구현 
  - [x] MSW를 활용하여 get, post 요청 모킹 
- [x] API 변경으로 인한 리팩터링 작업 

## Description
### New Plan Form에 필요한 컴포넌트 구현 
- `NumericInput` 컴포넌트: 운동의 Count와 Set를 입력할 수 있는 인풋입니다. 0에서 9까지의 숫자만 입력할 수 있도록 정규표현식을 적용하고, 앞자리에 0을 입력했을 때 0을 지워줄 수 있도록 구현했습니다.  

### Form Validation 
- `usePlanComplete` hook: workout plan table에 입력한 숫자들이 모두 0이 아닌 숫자로 채워져 있는지를 검증합니다. 

### 기존 컴포넌트 수정사항 - `SaveButton`에 disabled 속성 추가
- disabled일 때의 스타일은 적용되어 있었지만, 버튼 태그에 disabled 속성이 빠져있어서 이를 추가했습니다.

### 오타 수정 
- [AuthenticationCodeInput.tsx](https://github.com/Pullanner/pullanner-web/compare/feat/%2394-new-plan?expand=1#diff-1a2507b11b04c970582d7ceb3e2490cb16c7583bbabf331cd59b872abe49d956), [DeleteAccountModal.tsx](https://github.com/Pullanner/pullanner-web/compare/feat/%2394-new-plan?expand=1#diff-0301fcb307d68c5438b59db03e777125ee8cac094f7b947ff053ade8619fd34c), [src/pages/EditMyPage/index.tsx](https://github.com/Pullanner/pullanner-web/compare/feat/%2394-new-plan?expand=1#diff-747fb09bbf422566717a07d978668a5f320b3e29bf83fc3e63c6eb4de0a1b981), [src/pages/MyPage/LogoutModal.tsx](https://github.com/Pullanner/pullanner-web/compare/feat/%2394-new-plan?expand=1#diff-4b46983c9f6f08e0d6f06dbc93b900a7e918a7aa036b60286add69ffd320d6ed), [src/pages/MyPage/index.tsx](https://github.com/Pullanner/pullanner-web/compare/feat/%2394-new-plan?expand=1#diff-43e472eaffc0c7b53c268ce8a417e6d5898239fc4a55d6b1ac9b3df94eb7419f)에 있던 오타를 수정했습니다. 

### icons 폴더를 components 폴더에서 분리
- 아이콘은 UI 컴포넌트로서의 의미보다는 말 그대로 아이콘이라는, 일부 컴포넌트를 꾸미거나 강조하는 역할을 가지는 요소이기 때문에 컴포넌트 폴더에서 분리하는 것이 낫다고 판단하여, components 폴더와 같은 레벨로 옮겼습니다. 

## Visuals
- Toast 메시지는 Ant design을 적용했는데, 추후 변동을 염두에 두고 우선 적용했습니다.
https://github.com/Pullanner/pullanner-web/assets/85419343/ee821796-18b5-41d6-bbf8-0c1e2ba420e7

2023-09-05 17:22 UTC, soralee2821 requested changes
Plan의 상태가 복잡하고, Date 처리하기도 번거로우셨을텐데 잘 구현해주셨네요! 특히 커스텀 훅을 만들어서 재활용하는 부분 멋졌습니다ㅎㅎ 밀리 고생 많으셨습니다~!

2023-09-05 17:22 UTC, soralee2821 commented on src/components/PullUpCard/index.tsx
`SelectWorkout/WorkoutCard`와 `PullUpCard`을 비교해보니 내용이 같네요. `components` 폴더에 공통 스타일이 담긴 `Card` 컴포넌트를 만들어서 사용하면 좋을 것 같아요!

2023-09-05 17:22 UTC, soralee2821 commented on src/pages/Plan/PlanButtons/index.tsx
>          <span>💪 근력 키우기 플랜</span>
"근력 키우기 플랜" 문자열은 변경되는 값이 아니니까 상수 처리하면 좋을 것 같아요!

2023-09-05 17:22 UTC, soralee2821 commented on src/pages/Plan/PlanButtons/index.tsx
>          <span>🏆 동작 마스터 플랜</span>
이것도 위 문자열과 마찬가지로 상수 처리하면 좋을 것 같아요!

2023-09-05 17:22 UTC, soralee2821 commented on src/pages/NewPlan/index.tsx
> +};
**as const**를 붙여서 상수 처리하면 좋을 것 같아요!

2023-09-05 17:22 UTC, soralee2821 commented on src/pages/NewPlan/index.tsx
> +  const [selectedWorkouts, setSelectedWorkouts] = useState<Workout[]>([]);
React hook, Jotai hook, React-Router-DOM hook의 선언 순서에 대한 컨벤션으로 정하면 코드가 일관성 있어 보여서 더 좋을 것 같아요. 
저는 보통 React hook, Jotai hook, React-Router-DOM hook 순으로 선언하는 편입니다. 그 이유는 상태 관련 로직을 먼저 선언하고 그 외 다른 훅들은 그 이후에 선언하는 것이 상태가 바로 눈에 들어올 것 같아서입니다. 초반에 구현 순서대로 선언하거나 참조 순서 때문에 어쩔 수 없이 뒤죽박죽인 것도 있지만요ㅎㅎ;
밀리는 어떤 순서로 선언하는 걸 선호하시나요?

2023-09-05 17:22 UTC, soralee2821 commented on src/pages/NewPlan/index.tsx
> +              placeholder="운동 시각"
`TimePicker` 위의 문구로도 충분히 운동 시각을 설정하는 컴포넌트라는 것을 알 수 있어서, **placeholder**의 값으로 "운동 시각"보다는 "12:00"과 같은 값을 넣어주어서 사용자에게 적는 형식을 알려주는 것이 더 좋을 것 같아요!

2023-09-05 17:22 UTC, soralee2821 commented on src/components/WorkoutTable/WorkoutRow.tsx
> +        />
change 핸들러 함수를 **onChange** props로 받아서 `NumericInput` 컴포넌트를 재활용한 방식 멋지네요! 👍

2023-09-05 17:22 UTC, soralee2821 commented on src/utils/date.ts
> +  const utcDate = new Date(Date.UTC(year, month - 1, day, hour, minute));
이 코드에서 month에 1을 빼주는 이유가 궁금합니다.

2023-09-05 17:22 UTC, soralee2821 commented on src/components/WorkoutTable/hooks/useWorkout.tsx
> +  const [total, setTotal] = useState(0);
`total`은 `workoutCountSet`의 파생 상태여서  `workoutCountSet` 상태가 달라질 때마다 자동으로 변경되므로 상태로 선언하지 않아도 될 것 같습니다.

2023-09-05 17:22 UTC, soralee2821 commented on src/constants/plan.ts
`PLAN_TYPE`과 동일하게 `PLAN_MESSAGE`와 `NEW_PLAN_DESCRIPTION`에도 **as const** 키워드를 붙여주면 좋을 것 같아요!

2023-09-05 17:22 UTC, soralee2821 commented on src/pages/NewPlan/index.tsx
`NewPlan` 컴포넌트 내의 문자열들을 상수 처리하면 보기 좋을 것 같고, 파일이 너무 긴 것 같아서 분리 할 수 있는 부분이 있다면 컴포넌트로 분리했으면 좋겠습니다.

2023-09-05 17:22 UTC, soralee2821 commented on src/lib/axios/useAuthApi.ts
newPlan PR이 merge된 후에 `pathAuthRequest`도 동일한 에러 처리를 위해 `handleAuthRequest` 함수로 감싸서 호출하도록 수정해야 될 것 같아요!

2023-09-05 17:22 UTC, soralee2821 commented on src/mocks/plans/handler.ts
> +  const note = '';
`id`, `createdAt`, `prgress`, `note` 변수들은 상수이고, `newPlanData` 외에 다른 곳에 사용하지 않으므로, 따로 변수 선언을 하지 않고 `newPlanData` 내에서 해당 키에 대한 값을 할당해주는 건 어떠신가요?

2023-09-05 23:43 UTC, jaypedia commented on src/utils/date.ts
> +  const utcDate = new Date(Date.UTC(year, month - 1, day, hour, minute));
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

공식문서 참고해보시면 아시겠지만 다른것과 달리 month는 인덱스값으로 들어와야 하기 때문이에요~

2023-09-05 23:44 UTC, jaypedia commented on src/mocks/plans/handler.ts
> +  const note = '';
이부분은 취향의 차이인 것 같기도 하고 사실 실질적으로 production에서는 쓰이지 않는 부분이어서 크게 상관없다고 생각합니다! 
성능적인 문제가 따로 있는 게 아니라면요~

2023-09-05 23:45 UTC, jaypedia commented on src/pages/NewPlan/index.tsx
우선적으로 구현을 빠르게 하는 게 좋다 생각해서 일단은 이렇게 구현했습니다! 나중에 모달 등과 함께 리팩터링 할 때 같이 진행하면 좋을거같아요~

2023-09-05 23:47 UTC, jaypedia commented on src/pages/NewPlan/index.tsx
> +              placeholder="운동 시각"
그렇게 설정할 경우 이미 값이 세팅되어 있는 것으로 유저가 착각할 여지가 있어서 일부러 그렇게 하지 않았어요~
https://design.aetna.com/components/android/time-picker.html

참고해보시면 좋을거같습니다!

2023-09-05 23:48 UTC, jaypedia commented on src/pages/NewPlan/index.tsx
> +  const [selectedWorkouts, setSelectedWorkouts] = useState<Workout[]>([]);
이부분은 eslint 등으로 순서를 정렬할 수 있는 방안이 있으면 좋을거 같은데 그런 Rule은 찾지 못했네요!

2023-09-05 23:49 UTC, jaypedia commented on src/components/PullUpCard/index.tsx
이부분은 나중에 Pullup Detail 페이지 만들 때 반영할게요!

2023-09-06 01:21 UTC, soralee2821 commented on src/components/PullUpCard/index.tsx
마이페이지 리팩터링할 때 Card 컴포넌트를 사용할 예정이라 각자 분업하기 전에 하면 좋을 것 같아요. 단순히 파일을 옮기는 작업이니까 오늘 회의 때 하는건 어떠신가요?

2023-09-06 01:28 UTC, soralee2821 commented on src/pages/NewPlan/index.tsx
> +  const [selectedWorkouts, setSelectedWorkouts] = useState<Workout[]>([]);
eslint rule로 정하면, 참조 순서로 인한 예외 케이스도 순서를 강제해서 오류가 생길 것 같아서 저희끼리 논의한 후 신경 써서 선언하면 될 것 같아요!

2023-09-06 01:39 UTC, soralee2821 commented on src/pages/NewPlan/index.tsx
> +              placeholder="운동 시각"
그러면 이전의 p 태그에 "풀업 시간을 12:00의 형태로 적어주세요"와 같은 문구를 추가해서 사용자에게 적는 형식을 알려주는 것 어떤가요? TimePicker를 처음 봤을 때 어떤 형식으로 적을지 모를 수 있을 것 같다는 생각이 들어서 직간접적으로 그에 대한 설명이 있으면 좋을 것 같습니다.

2023-09-06 01:40 UTC, soralee2821 commented on src/utils/date.ts
> +  const utcDate = new Date(Date.UTC(year, month - 1, day, hour, minute));
한국시간과의 오프셋만 생각했었는데, 매개변수 형식 차이였군요! 덕분에 하나 더 알아갑니다ㅎㅎ

2023-09-06 06:25 UTC, jaypedia commented on src/pages/NewPlan/index.tsx
> +  const [selectedWorkouts, setSelectedWorkouts] = useState<Workout[]>([]);
이부분은 추후 리팩터링할 때 간소화되는 여지가 있어서, 일단은 넘어가도록 하겠습니다.

2023-09-07 09:02 UTC, merged