Feat/#104 my page
Pullanner/pullanner-web pull request #107
Opened 2023-09-13 11:08 UTC by soralee2821

## Issues
- Issue number #104 

## Tasks Done 
- [x] 마이페이지 UI 수정
  - [x] 프로필 이미지와 정보(닉네임, 이메일)을 가로로 배치
  - [x] "정보수정" 버튼 삭제
  - [x] **userCount**를 **planCount**로 변경 (이전에 변경된 User 데이터 반영)
- [x] 헤더 클릭 시 Dropdown이 나오도록 변경
  - [x] Dropdown의 "정보수정" 버튼 클릭 시 `EditMyPage`로 이동
  - [x] Dropdown의 "로그아웃" 버튼 클릭 시 `LogoutModal`을 보여줌
  - [x] Dropdown의 "커뮤니티 활동" 버튼 클릭 시 커뮤니티 활동 페이지(임시)로 이동
- [x] `ProgressBar` UI 변경
  - [x] **level**, 퍼센트 UI 추가
  - [x] 여백 조정
- [x] "나의 풀업 현황" 추가
  - [x] User Workout GET API를 통해 풀업 운동 데이터 가져오기
  - [x] 컴포넌트 구현하기
  - [x] 수정 아이콘 추가
- [x] 풀업 현황 수정 페이지 구현
  - [x] "저장" 버튼 클릭시 Workout POST API 호출

## Description
### MyPage UI 수정
- `UserSection`에서 프로필 이미지와 사용자 정보들을 가로 배치로 변경했습니다.
- `ProgressSection`에서 `ProgressBar`와 그에 대한 설명의 위치를 변경했습니다.
  - `ProgressBar`에서 퍼센트 수치를 추가했습니다.
- 더 이상 필요 없는 `TabSection`과 `LogoutButton`을 삭제했습니다.

<br>

### ProfileImageDropdown 추가
- `Header` 컴포넌트에서 로그인 상태 여부에 따라 프로필 이미지 기능을 다르게 구현했습니다.
  - 로그인 상태일 때, `ProfileImageDropdown` 컴포넌트를 렌더링합니다.
  - 로그아웃 상태일 때, 로그인 페이지로 이동하는 **Link** 컴포넌트를 렌더링합니다.
- `ProfileImageDropdown` 컴포넌트를 클릭했을 때 "프로필", "정보수정", "커뮤니티 활동", "로그아웃" 메뉴가 나오도록 구현했습니다.
  - "프로필" 메뉴는 클릭 시 `MyPage`로 이동하는 **Link** 컴포넌트입니다.
  - "정보수정" 메뉴는 클릭 시 `EditMyPage`로 이동하는 **Link** 컴포넌트입니다.
  - "로그아웃" 메뉴는 클릭 시 `LogoutModal`을 띄우는 **button** 컴포넌트입니다.

<br>

### MyPage에 나의 풀업 현황(Workout)을 추가
- 나의 풀업 현황을 나타내는 `WorkoutSection`을 구현했습니다.
  - 초반에는 **Workout GET** API를 호출하는 **useGetWorkoutData** 함수를 사용하여 풀업 현황을 나타냈습니다.
    - 그러나 네트워크 응답 대기 시간 때문에 수정된 풀업 현황이 느리게 반영되고, `MyPage`에 방문할 때마다 **Workout GET** API를 호출하는 것이 비효율적이라고 생각했습니다.
  - 따라서 **workoutDataAtom**을 사용해서 풀업 현황을 나타냈습니다.
  - 그리고 로그인 후 콜백 페이지인 `LoginLoading`에서 **useGetWorkoutData** 함수의 반환값을 **workoutDataAtom**에 저장하도록 수정했습니다.
    - **hanging** 풀업 운동은 선택되어 있어야 하기 때문에,  **useGetWorkoutData** 함수의 반환값이 빈 배열이 아닌 경우에만 **workoutDataAtom**에 저장하도록 변경했습니다.
- `WorkoutSection`의 배치를 위해 `UserSection`과 `ProgressSection`의 padding값을 수정했습니다.

<br>

### 풀업 현황 수정 페이지 EditWorkout 구현
- `MyPage`의 풀업 현황을 수정하는 `EditWorkout` 페이지를 구현했습니다.
- "저장" 버튼 클릭 시 **Workout POST** API를 호출하고 `MyPage`로 이동하도록 구현했습니다.
- `SelectWorkout`과 `EditWorkout`의 풀업 현황이 동일하므로, 풀업 현황을 `SelectableWorkoutDashboard` 컴포넌트로 추출하여 재활용하도록 리팩터링했습니다.
- 스크롤 바가 나오지 않도록 `EditMyPage` 요소들의 padding값을 수정했습니다.

<br>

### 기타 리팩터링
- `EditMyPage`에서 **userData**가 null인 경우 조건문 추가
  - `EditMyPage`에서 **로그아웃**을 할 경우, **userData**가 null로 초기화됩니다.
  - **userData**가 null인 경우 구조 분해 할당을 할 수 없으므로, **userData**가 null인 경우를 조건문으로 걸러준 후에 구조 분해 할당하도록 수정했습니다.
- **Card** 관련 컴포넌트들을 `cards` 폴더로 이동
  - `WorkoutCard`, `SelectablePullupCard`, `SelectableWorkoutCard` 컴포넌트들을 `cards` 폴더로 이동했습니다.
- 현재 **User** API에 맞게 **userData**에서 **journalCount**를 **planCount**로 수정했습니다.
- 배포 환경에서 `usePlans` 파일 오류 수정
  - `useGetAllPlans`, `useGetPlanById`, `usePostPlan` 함수에 **setModalType** 매개변수로 추가했습니다.
  - `useGetAllPlans`, `usePostPlan` 함수 호출문에 **setModalType** 인수를 추가했습니다.

<br>

## 추후 추가할 부분
- **userData**에 가입일을 나타내는 **joinDate** 추가 (**User** API 변경 후 적용)
- **userData**의 **planCount**를 **experiencePoint**로 변경 (**User** API 변경 후 적용)
<br>

## Visuals

![MyPage](https://github.com/Pullanner/pullanner-web/assets/70058081/5a8a9b32-41f8-4eb6-9e3b-4658ee645c44)

2023-09-13 23:21 UTC, jaypedia requested changes
마이페이지가 점점 끝이 보이는군요! 고생 많으셨어요 에스~! 조금만 더 힘내봅시다 💪

2023-09-13 23:21 UTC, jaypedia commented on src/components/ProgressBar/index.tsx
> +      <span className="float-right pr-1.5 text-xs text-black">{`${percent}%`}</span>
오 float를 쓰셨군요!

2023-09-13 23:21 UTC, jaypedia commented on src/components/SelectableWorkoutDashboard/index.tsx
> +        <p className="pb-5 font-bold text-primary">{`현재 가능한 풀업 동작 : ${workoutData.size}`}</p>
현재 가능한 풀업 동작의 개수를 표현한 거니까, '현재 가능한 풀업 동작 수' 라고 명시하는 거 어떨까요?

2023-09-13 23:21 UTC, jaypedia commented on src/pages/MyPage/WorkoutSection.tsx
> +const TEXT_CONTENTS = '나의 풀업현황';
'풀업 현황'으로 띄어쓰기 부탁드려요~

2023-09-13 23:21 UTC, jaypedia commented on src/pages/MyPage/WorkoutSection.tsx
> +    <section className="w-full bg-[#1E1E1E] p-5 text-center">
bg-[#1e1e1e] 이렇게 되어 있는 것들 색상 정리를 한번 싹 하면 좋을거같아요! IDE의 힘을 빌려서 한꺼번에 리팩터링을.. 앞으로 개발할 것도 많으니까, 지금 조금 시간을 내서 해도 괜찮을 것 같다는 의견입니다.

2023-09-14 02:01 UTC, soralee2821 commented on src/components/ProgressBar/index.tsx
> +      <span className="float-right pr-1.5 text-xs text-black">{`${percent}%`}</span>
네, ProgressBar 위에 퍼센트 글자를 띄워야 되서 float를 사용했습니다.

2023-09-14 02:02 UTC, soralee2821 commented on src/components/SelectableWorkoutDashboard/index.tsx
> +        <p className="pb-5 font-bold text-primary">{`현재 가능한 풀업 동작 : ${workoutData.size}`}</p>
네, 그렇게 수정하겠습니다!

2023-09-14 02:02 UTC, soralee2821 commented on src/pages/MyPage/WorkoutSection.tsx
> +const TEXT_CONTENTS = '나의 풀업현황';
넵, 그렇게 수정할께요~

2023-09-14 02:03 UTC, soralee2821 commented on src/pages/MyPage/WorkoutSection.tsx
> +    <section className="w-full bg-[#1E1E1E] p-5 text-center">
좋은 의견입니다!

2023-09-14 22:33 UTC, jaypedia commented on tailwind.config.cjs
> +        sectionBackground: '#1E1E1E',
제가 말씀드린 색상 상수화는 

```
  'grey-9': '#1E1E1E',
  'grey-8': '#3F3F3F',
  'grey-7': '#606060',
  'grey-6': '#A0A0A0',
  'grey-5': '#C6C6C6',
  'grey-4': '#DCDADA',
  'grey-3': '#E8E8E8',
  'grey-2': '#F4F4F4',
  'grey-1': '#F8F8F8',
```
이런 식으로 하자는 것이었어요!
grey컬러 같은 경우엔 워낙 종류가 많아서 일일이 이름을 붙여주는 것보다 이렇게 디자인 시스템을 만들어서 설정해놓으면 좋을거같아요
디자이너분과 이야기해도 좋고요!

2023-09-15 09:29 UTC, soralee2821 commented on tailwind.config.cjs
> +        sectionBackground: '#1E1E1E',
네, 그럼 디자이너와 논의해서 자세히 정하면 좋을 것 같아요!

2023-09-15 10:19 UTC, merged