Refactor/#116 summary
Pullanner/pullanner-web pull request #117
Opened 2023-11-08 07:43 UTC by soralee2821

## Issues
- Issue number #116 

## Tasks Done 
- API 인터페이스의 변경 사항 적용
  - [x] 월별 풀업 운동 횟수 데이터 API의 인터페이스 변경 사항 적용
  - [x] 운동 시간대별 완료된 플랜 갯수 데이터 API의 인터페이스 변경 사항 적용
- 영어 이름을 한글 이름으로 변경
  - [x] 월별 풀업 운동 횟수 그래프의 X, Y 축, 문구를 한글로 변경
  - [x] 운동 시간대별 완료된 플랜 갯수 그래프의 X, Y 축, 문구를 한글로 변경

<br>

## Description
### 월별 풀업 운동 횟수 데이터 API의 인터페이스 변경 사항 적용
- "data" 키와 기존 데이터 값을 가진 객체 형태의 데이터로 변경했습니다.
- "month" 키에 대한 값을 달 영어 이름 대문자 3글자로 변경했습니다. ("Jun" => "JUN")

```json
{
    "data": {
        "Hanging": [
            {
                "month": "JUN",
                "totalCount": 0
            },
            {
                "month": "JUL",
                "totalCount": 0
            },
            {
                "month": "AUG",
                "totalCount": 0
            },
            {
                "month": "SEP",
                "totalCount": 0
            },
            {
                "month": "OCT",
                "totalCount": 0
            },
            {
                "month": "NOV",
                "totalCount": 0
            }
        ],
        ...
    }
}
```

### 월별 풀업 운동 횟수 그래프의 X, Y 축, 문구를 한글로 변경
- Pullanner 서비스의 주 타겟층이 한국인이므로, 그래프의 X, Y 축, 문구를 한글로 변경했습니다.
- 문구에서 달에 대한 전체 영어 이름을 사용하기 위해 만든 객체 `FULL_MONTH_NAME_BY_ABBREVIATION`를 없애고, 달에 대한 한글 이름을 가진 객체 `MONTH_NAME_IN_KOREAN`를 만들어서 사용했습니다.
- 월별 풀업 운동 횟수 그래프의 X, Y 축인 "month", "totalCount"를 "월", "운동 횟수"로 변경했습니다.
- `MONTH_NAME_IN_KOREAN` 통해 월별 풀업 운동 횟수 그래프의 X 축 값인 달 이름을 한글로 변경했습니다.
- tooltip에서 달 이름을 한글로 작성하니까 여백이 많이 남아서, 달 이름과 운동 횟수를 flex 박스로 감싸서 한 줄로 변경했습니다.

### 운동 시간대별 완료된 플랜 갯수 데이터 API의 인터페이스 변경 사항 적용
- 화면에서 명시한 운동 시간대와 실제 운동 시간대가 달라서 혼돈을 줄 수 있다고 생각하여 하루에 대한 운동 시간대를 4로 나누는 것을 제안했습니다. [참고](https://www.notion.so/dev-millie/Summary-API-e3f1cfaac4de4f0baa009ad987214e9e)
- 기존 운동 시간대(moring, afternoon, evening)에서 night를 추가했습니다.
- 운동 시간대의 시간 범위를 아래와 같이 수정했습니다.
  - night : 00:00 ~ 05:59
  - morning : 06:00 ~ 11:59
  - afternoon : 12:00 ~ 17:59
  - evening : 18:00 ~ 23:59

```json
{
 "completedPlanCountByTime" : [
    {
      "time": "night",
      "thisMonth": 40,
      "prevMonth": 45,
    },
    {
      "time": "morning",
      "thisMonth": 20,
      "prevMonth": 10,
    },
    {
      "time": "afternoon",
      "thisMonth": 30,
      "prevMonth": 35,
    },
    {
      "time": "evening",
      "thisMonth": 70,
      "prevMonth": 55,
    },
  ],
}
```

### 운동 시간대별 완료된 플랜 갯수 그래프의 X, Y 축, 문구를 한글로 변경
- Pullanner 서비스의 주 타겟층이 한국인이므로, 그래프의 X, Y 축, 문구를 한글로 변경했습니다.
- 시간대에 대한 한글 이름을 가진 객체 `TIME_NAME_IN_KOREAN`를 만들어서 사용했습니다.
- 운동 시간대별 완료된 플랜 갯수 그래프의 X, Y1, Y2 축인 "time", "thisMonth", "prevMonth"를 "시간대", "이번달 플랜수", "저번달 플랜수"로 변경했습니다.
- `TIME_NAME_IN_KOREAN`를 통해 운동 시간대별 완료된 플랜 갯수 그래프의 X 축 값인 운동 시간대를 한글로 변경했습니다.
- 운동 시간대별 완료된 플랜 갯수 그래프의 width를 350에서 330으로 줄였습니다.

<br>

## Visuals
### 월별 풀업 운동 횟수 그래프

<img width="188" alt="image" src="https://github.com/Pullanner/pullanner-web/assets/70058081/5757838b-8855-4284-b2a0-3b06eb92e9f9">
<img width="189" alt="스크린샷 2023-11-08 163629" src="https://github.com/Pullanner/pullanner-web/assets/70058081/1b9d8219-0f17-488d-9c74-9efece7235b2">

### 운동 시간대별 완료된 플랜 갯수 그래프

<img width="187" alt="스크린샷 2023-11-08 164108" src="https://github.com/Pullanner/pullanner-web/assets/70058081/f7bd75b1-df07-4be0-8045-be1bb0ac17c3">
<img width="186" alt="image" src="https://github.com/Pullanner/pullanner-web/assets/70058081/02483828-2c0e-40fa-a67f-d05353cbe473">

2023-11-08 15:18 UTC, jaypedia requested changes

2023-11-08 15:18 UTC, jaypedia commented on src/pages/Summary/CompletedPlanCountByTimeChart/index.tsx
> +        <Bar dataKey="저번달 플랜수" fill="#8D8D8D" />
'플랜 수'라고 띄어쓰기가 되어야할 것 같아요~

2023-11-08 15:28 UTC, soralee2821 commented on src/pages/Summary/CompletedPlanCountByTimeChart/index.tsx
> +        <Bar dataKey="저번달 플랜수" fill="#8D8D8D" />
네, 그렇게 수정해서 다시 커밋할께요!

2023-11-09 13:29 UTC, jaypedia approved these changes
고생 많으셨습니다!!

2023-11-09 13:29 UTC, merged