Feat/#47 modal
Pullanner/pullanner-web pull request #58
Opened 2023-07-18 10:45 UTC by soralee2821

## Issues
- Issue number #47 

## Tasks Done 
- [x] **createPortal** API를 사용하여 `Modal` 컴포넌트 구현
- [x] `Modal` 컴포넌트 안에 들어갈 `Modal Button`, `Prompt Text` 컴포넌트 구현

## Description
- 형식이 정해진 라이브러리를 사용하는 대신 React의 **createPortal** API를 사용하여 범용적인 Modal 컴포넌트를 구현했습니다.
  - `Modal` 컴포넌트의 **children** props를 받아서 자식 컴포넌트들을 합성하여 사용할 수 있도록 했습니다.
- `Modal`에 들어갈 버튼인 `ModalButton` 컴포넌트를 구현했습니다.
  - **text**, **handler** props를 받아서 여러 버튼 컴포넌트로 재사용할 수 있도록 구현했습니다.
  - **imageUrl** props를 받을 경우, `ModalButton` 컴포넌트의 자식 컴포넌트로 **img** 요소를 렌더링하도록 했습니다.
  - **isFocused** props의 값으로 true를 받을 경우, `ModalButton` 컴포넌트의 **button** 요소에 포커스가 되도록 했습니다.
- `Modal`에 들어갈 텍스트를 담을  `PromptText` 컴포넌트를 구현했습니다.
  - `PromptText` 컴포넌트의 **children** props를 받아서 자식 컴포넌트들을 합성하여 사용할 수 있도록 했습니다.

## Visuals

<img width="191" alt="스크린샷 2023-07-18 194310" src="https://github.com/Pullanner/pullanner-web/assets/70058081/c62ba6b3-4534-4134-9ca8-776596995f33">

2023-07-19 00:50 UTC, jaypedia requested changes
Modal 컴포넌트를 합성 컴포넌트로 하면 좋겠다는 제안을 잘 받아주시고 구현을 잘 해주셨네요! 고생 많으셨어요👍 논의할 부분만 좀 더 논의 후 바로 머지하면 될 것 같아요.

2023-07-19 00:50 UTC, jaypedia commented on src/components/Modal/ModalButton.tsx
> +  }, [isFocused]);
useEffect 대신에 useLayoutEffect를 쓰신 이유도 PR에 포함해주실 수 있나요?

그리고 formatting에 관련한 이야긴데 return문과 한 줄 띄워서 작성하면 가독성이 좀 더 좋아질 것 같습니다. 저는 보통 컴포넌트 내에 함수 같은 것을 사용한다면 return문 사이에 공백 빈 줄을 넣거든요. 상의 후 컨벤션으로 지정해도 좋을 것 같아요~

2023-07-19 00:50 UTC, jaypedia commented on src/constants/routePath.ts
> +  withdrawal: '/withdrawal',
withdrawal 페이지는 따로 구현을 하실 예정인가요?

2023-07-19 00:54 UTC, soralee2821 commented on src/components/Modal/ModalButton.tsx
> +  }, [isFocused]);
모달이 띄워졌을 때 '아니오' 버튼에 포커스가 되어 있어야 하기 때문에, 마운트가 된 후 실행되는 useEffect 대신에 마운트 전에 실행되는 useLayoutEffect를 사용했습니다.
return 사이에 공백 넣는 거 좋습니다.

2023-07-19 00:55 UTC, soralee2821 commented on src/constants/routePath.ts
> +  withdrawal: '/withdrawal',
withdrawal은 회원탈퇴 페이지입니다. 논의했을 때 회원탈퇴도 페이지로 빼자고 하셔서 ROUTE_PATH에 추가했습니다.

2023-07-19 01:10 UTC, jaypedia commented on src/components/Modal/ModalButton.tsx
> +  }, [isFocused]);
padding-line-between-statements를 적용하면 되겠네요! 

https://eslint.org/docs/latest/rules/padding-line-between-statements

2023-07-20 05:06 UTC, jaypedia requested changes

2023-07-20 05:06 UTC, jaypedia commented on src/components/Modal/index.tsx
> +      <div className="flex h-[100%] w-[100%] items-center justify-center bg-black/50 sm:h-[50rem] sm:max-h-[90vh] sm:w-96">
bg-black/50 이런 식으로도 opacity를 조절할 수 있다는 걸 알았네요! 

https://tailwindcss.com/docs/background-color#changing-the-opacity

여기서도 나오는군요 ㅎㅎ 덕분에 알아갑니다
이부분이 모달의 background가 dim 처리 된 부분인가요?

더불어 dim 처리 된 것이 반영될 수 있도록 Visuals에 추가해주시면 좋을 것 같습니다!

2023-07-20 05:07 UTC, jaypedia requested changes

2023-07-20 05:07 UTC, jaypedia commented on src/components/Modal/index.tsx
> +        <div className="z-50 flex flex-col items-center justify-center rounded-md bg-[#202020] p-5">
고정값으로 주셨던 height, width를 제거하셨네요 굿!

2023-07-20 05:11 UTC, soralee2821 commented on src/components/Modal/index.tsx
> +      <div className="flex h-[100%] w-[100%] items-center justify-center bg-black/50 sm:h-[50rem] sm:max-h-[90vh] sm:w-96">
네, bg-black/50이 opacity 0.5로 수정한 부분 맞습니다. Visuals 반영해서 변경할께요.

2023-07-20 05:23 UTC, jaypedia requested changes

2023-07-20 05:23 UTC, jaypedia commented on src/pages/EditMyPage/index.tsx
> +            <p className="mb-2.5 text-xs">
모달 버튼의 폰트 크기는 text-sm인데, prompt text의 크기는 text-xs네요! 버튼 안의 텍스트가 더 큰 것이 시각적으로 약간 어색해 보이기도 합니다. 

![image](https://github.com/Pullanner/pullanner-web/assets/85419343/bf84ddea-efb5-4831-9480-257480502f3b)

아니면 위와 같은 예시로 메인 텍스트는 사이즈를 좀 더 크게 하고, 서브 텍스트는 크기를 작게 하면 UI가 좀 더 자연스러우면서도 유저에게 잘 알릴 수 있을 것 같아요.

2023-07-20 06:05 UTC, soralee2821 commented on src/pages/EditMyPage/index.tsx
> +            <p className="mb-2.5 text-xs">
PromptText의 글자 크기가 **text-xs**인 이유는 "회원 탈퇴 시 Pullanner의 모든 데이터가 삭제됩니다." 문구에서 마지막 글자인 "다"만 다음 줄로 넘어가는 것이 미관 상 안좋아보여서 글자 크기를 줄인 것이었습니다.
그런데 PromptText의 글자 크기가 ModalButton의 글자 크기보다 작으면 안 되겠네요. 반영해서 수정하겠습니다.
MainText와 SubText를 분리해서 CSS를 다르게 주도록 변경해보겠습니다.

2023-07-20 06:06 UTC, soralee2821 commented on src/pages/EditMyPage/index.tsx
> +            <p className="mb-2.5 text-xs">
MainText와 SubText를 나눠서 구현하는 방법 좋습니다!

2023-07-21 04:17 UTC, jaypedia approved these changes

2023-07-21 04:17 UTC, jaypedia commented on src/pages/EditMyPage/index.tsx
> +          <div className="mb-2 flex w-full justify-around p-3">
확실피 마진 추가하니까 UI가 낫네요! 👍

2023-07-21 04:17 UTC, merged