Feat/#93 delete account timer
Pullanner/pullanner-web pull request #95
Opened 2023-08-22 12:57 UTC by soralee2821

## Issues
- Issue number #93

## Tasks Done 
- [x] 타이머 리셋 기능 구현
  - [x] 타이머 관련 전역 상태로 **timerStateAtom**를 선언
  - [x]  **timerStateAtom**의 **reset** 속성이 true일 때, **timeSpan** state를 초기화
- [x] `DeleteAccount`와 `AuthenticationCodeInput` 컴포넌트에 `timerStateAtom` 적용
  - [x] **isTimerActive** 변수를 **timerStateAtom**의 **isVisble** 속성으로 변경
  - [x] **"인증코드 전송하기"** 버튼 클릭 시 조건문 추가
    - [x]  **isVisble**이 true면, **reset**을 true로 설정하여 `Timer`를 리셋함
    - [x]  **isVisble**이 false면, **isVisible**을 true로 설정하여 `Timer`를 보여줌
  - [x] 회원탈퇴 완료 모달의 **"확인"** 버튼 클릭 시 **timerStateAtom** 값 초기화 

## Description
### timerStateAtom 선언
- 이유 : `DeleteAccount`, `AuthenticationCodeInput`, `Timer` 순으로 depth 2 이상으로 상태를 공유하고 있기 때문에, 전역 상태로 선언하여 **props drilling**을 없앴습니다.
- **timerStateAtom**은 **isVisble**과 **reset** 속성을 가진 객체입니다.
  - **isVisble**이 true일 경우, `Timer` 컴포넌트를 렌더링합니다.
  - **reset**이 true일 경우, `Timer` 컴포넌트의 **setInterval**을 초기화합니다.

### useTimer 훅 수정
- **setInterval**을 초기화하기 위해, **setInterval**의 id를 저장할 **intervalIdRef**를 선언했습니다.
  - **intervalIdRef**의 타입을 쉽게 설정하기 위해서 반환 타입이 `NodeJs.Timer`인 **setInterval** 대신 `number` 타입인 **window.setInterval**을 사용했습니다.
-  **timerStateAtom**의 **reset** 속성이 true인 경우, **intervalIdRef.current**를 사용하여 setInterval을 취소하고 **timeSpan** 상태를 제한 시간으로 초기화했습니다.
- `useTimer` 훅을 구독하고 있는 컴포넌트가 언마운트될 때, **setInterval**이 취소하는 클린업 함수가 작성된 `useEffect` 훅을 추가했습니다.

### DeleteAccount, AuthenticationCodeInput 컴포넌트에 timerStateAtom 적용
- `DeleteAccount` 컴포넌트의 **isTimerActive** 상태를 **timerStateAtom**의 **isVisible** 속성으로 교체했습니다.
- `DeleteAccount` 컴포넌트의 **"인증코드 전송하기"** 버튼을 클릭했을 때, **timerStateAtom**의 **isVisible** 속성에 따른 조건문을 추가했습니다.
  - **timerStateAtom**의 **isVisible** 속성이 true라면, 현재 실행 중인 `Timer`가 존재하므로 **timerStateAtom**의 **reset** 속성을 true로 설정하여 `Timer`가 리셋되도록 구현했습니다.
  - **timerStateAtom**의 **isVisible** 속성이 false라면, 현재 실행 중인 `Timer`가 없으므로 **timerStateAtom**의 **isVisible** 속성을 true로 설정하여 `Timer`를 렌더링하도록 구현했습니다.
- `AuthenticationCodeInput` 컴포넌트의 회원 탈퇴 완료 모달의 **"확인"** 커튼을 클릭했을 때, **timerStateAtom**의 **isVisible**, **reset** 속성이 false로 초기화되도록 구현했습니다.

## Visuals
![resetTimer](https://github.com/Pullanner/pullanner-web/assets/70058081/00e710c6-bfa3-4bbc-8d53-72aed155b27b)

2023-08-22 13:34 UTC, jaypedia requested changes
'인증코드 발송하기' 버튼을 클릭하고, 3분 동안은 해당 버튼을 비활성화해서 여러 번 클릭할 수 없도록 처리가 필요할 것 같습니다!

2023-08-22 13:34 UTC, jaypedia commented on src/hooks/useTimer.ts
> +      clearInterval(intervalIdRef.current);
바로 위에 useEffect에도 같은 코드를 return하고 있는데, 두 번 적으신 이유가 있으신가요?

2023-08-22 13:51 UTC, soralee2821 commented on src/hooks/useTimer.ts
> +      clearInterval(intervalIdRef.current);
첫 번째 useEffect의 clearInterval는 1초마다 실행한 setInterval에 대한 cleanup 함수이고, 두 번째 useEffect의 clearInterval는 useTimer 함수를 구독한 컴포넌트가 언마운트될 때 setInteval에 대한 cleanup 함수입니다.
첫 번째 useEffect의 clearInterval로 setInterval가 취소될 줄 알았는데, 다른 페이지로 이동해서 setInterval이 실행되고 있더라고요.
[이 글](https://stackoverflow.com/questions/66043252/react-hooks-useinterval-reset-after-button-click)을 참고해서 언마운트될 때에 대한 cleanup 함수를 추가했습니다.

2023-08-22 13:56 UTC, soralee2821 commented
> 

버튼 중복 클릭 방지 처리 좋은 생각입니다! 👍
혹시 3분이라고 생각하신 근거가 있으실까요?
중복 클릭 방지 시간 내에 클릭할 경우, 그 이후 클릭을 유도하는 문구도 같이 보여주면 좋을 것 같아요!

2023-08-22 13:57 UTC, jaypedia commented
> > 
> 
> 버튼 중복 클릭 방지 처리 좋은 생각입니다! 👍 혹시 3분이라고 생각하신 근거가 있으실까요? 중복 클릭 방지 시간 내에 클릭할 경우, 그 이후 클릭을 유도하는 문구도 같이 보여주면 좋을 것 같아요!

인증번호를 입력할 수 있는 제한시간이 3분이고, 그 시간이 지난 후에 새로운 인증번호를 요청할 수 있는 것이 자연스럽다고 생각해서였어요!

2023-08-22 14:21 UTC, jaypedia requested changes

2023-08-22 14:21 UTC, jaypedia commented on src/hooks/useTimer.ts
> +      clearInterval(intervalIdRef.current);
아하 그렇게 cleanup이 두 번 이뤄져야하는군요! 링크까지 첨부해 주신 덕분에 잘 알아갑니다!

그런데 부가적으로 상단에는 const id = intervalIdRef.current; 이런 식으로 id라는 변수에 저장해놓고, 하단 useEffect는 그러지 않으셨는데 일관성을 유지하는 쪽으로 작성하면 좋을거 같습니다.

2023-08-23 01:33 UTC, soralee2821 commented
제한시간 3분 후부터 "인증코드 전송하기" 버튼이 활성화되는 것이면 **reset** 관련 기능이 필요 없겠네요.
이 PR을 닫고 다시 구현해서 PR 올리겠습니다!

2023-08-23 01:34 UTC, closed without merging

2023-08-23 01:40 UTC, soralee2821 commented on src/hooks/useTimer.ts
> +      clearInterval(intervalIdRef.current);
네, 그러면 다음 PR에 `intervalIdRef.current`를 사용하여 **setInterval**을 취소하는 것으로 일관성을 유지하겠습니다!